### ISSUE TITLE
How can I build this module?

### ISSUE THREAD

**Issue by only-gale** [noemi-salaun/ng2-logger#1]
After I run `npm run bundle`, I got some errors below:

`gale@gale-ThinkPad-T450s:~/Documents/github/angular2-components/ng2-logger$ npm run bundle

> @nsalaun/ng2-logger@1.0.2 bundle /home/gale/Documents/github/angular2-components/ng2-logger
> npm run clear && npm test && npm run ngc && npm run rollup && npm run rollup:min

> @nsalaun/ng2-logger@1.0.2 clear /home/gale/Documents/github/angular2-components/ng2-logger
> npm run clear:ngc && npm run clear:css && npm run clear:bundle && npm run clear:test

> @nsalaun/ng2-logger@1.0.2 clear:ngc /home/gale/Documents/github/angular2-components/ng2-logger
> npm run clear:tsc && npm run clear:metadata

> @nsalaun/ng2-logger@1.0.2 clear:tsc /home/gale/Documents/github/angular2-components/ng2-logger
> npm run clear:js && npm run clear:dts

> @nsalaun/ng2-logger@1.0.2 clear:js /home/gale/Documents/github/angular2-components/ng2-logger
> find src -type f \( -iname '*.js' -o -iname '*.js.map' \) -delete && rm -f index.js index.js.map

> @nsalaun/ng2-logger@1.0.2 clear:dts /home/gale/Documents/github/angular2-components/ng2-logger
> find src -type f -iname '*.d.ts' -delete && rm -f index.d.ts

> @nsalaun/ng2-logger@1.0.2 clear:metadata /home/gale/Documents/github/angular2-components/ng2-logger
> find src -type f -iname '*.metadata.json' -delete && rm -f index.metadata.json

> @nsalaun/ng2-logger@1.0.2 clear:css /home/gale/Documents/github/angular2-components/ng2-logger
> find src -type f \( -iname '*.css' -o -iname '*.css.map' \) -delete

> @nsalaun/ng2-logger@1.0.2 clear:bundle /home/gale/Documents/github/angular2-components/ng2-logger
> rm -rf bundles

> @nsalaun/ng2-logger@1.0.2 clear:test /home/gale/Documents/github/angular2-components/ng2-logger
> find test -type f \( -iname '*.js' -o -iname '*.js.map' -o -iname '*.d.ts' \) -delete

> @nsalaun/ng2-logger@1.0.2 test /home/gale/Documents/github/angular2-components/ng2-logger
> npm run karma:once

> @nsalaun/ng2-logger@1.0.2 karma:once /home/gale/Documents/github/angular2-components/ng2-logger
> npm run tsc && karma start karma.conf.js --single-run

> @nsalaun/ng2-logger@1.0.2 tsc /home/gale/Documents/github/angular2-components/ng2-logger
> tsc

error TS6053: File '/home/gale/Documents/github/angular2-components/ng2-logger/typings/index.d.ts' not found.

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "tsc"
npm ERR! node v6.3.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @nsalaun/ng2-logger@1.0.2 tsc: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @nsalaun/ng2-logger@1.0.2 tsc script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @nsalaun/ng2-logger package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @nsalaun/ng2-logger
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @nsalaun/ng2-logger
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gale/Documents/github/angular2-components/ng2-logger/npm-debug.log

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "karma:once"
npm ERR! node v6.3.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @nsalaun/ng2-logger@1.0.2 karma:once: `npm run tsc && karma start karma.conf.js --single-run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @nsalaun/ng2-logger@1.0.2 karma:once script 'npm run tsc && karma start karma.conf.js --single-run'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @nsalaun/ng2-logger package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run tsc && karma start karma.conf.js --single-run
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @nsalaun/ng2-logger
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @nsalaun/ng2-logger
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gale/Documents/github/angular2-components/ng2-logger/npm-debug.log
npm ERR! Test failed.  See above for more details.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "bundle"
npm ERR! node v6.3.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @nsalaun/ng2-logger@1.0.2 bundle: `npm run clear && npm test && npm run ngc && npm run rollup && npm run rollup:min`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @nsalaun/ng2-logger@1.0.2 bundle script 'npm run clear && npm test && npm run ngc && npm run rollup && npm run rollup:min'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @nsalaun/ng2-logger package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clear && npm test && npm run ngc && npm run rollup && npm run rollup:min
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @nsalaun/ng2-logger
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @nsalaun/ng2-logger
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gale/Documents/github/angular2-components/ng2-logger/npm-debug.log`

What does this mena?

**Comment by chunghha** [comment]
@only-gale after checking out, this works.

`npm i && ./node_modules/.bin/typings i && npm run bundle`

so seems you missed to run **typings install**.

**Comment by only-gale** [comment]
Got it, thx.
